# Welcome to Jekyll!
#

# Site settings
title: David Martellock
description: |
  Compulsive Creativity
  
owner: David Martellock # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: David@Martellock.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://martellock" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  linkedin-square: https://linkedin.com/in/davidmartellock
  github: https://github.com/DSBMartellock
  #facebook-official: https://facebook.com/dsbmartellock
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:David@Martellock.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  soundcloud: https://soundcloud.com/staypositiveaddlove
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

theme: jekyll-theme-slate
